config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => ENV['SIGN_IN'], :sign_out => ENV['SIGN_OUT'], :sign_up => ENV['SIGN_UP']}

  root to: "homepage#index"

  resources :homepage
  resources :services
  resources :packages_and_prices
  resources :contacts, only: [:new, :create]
  resources :preview_pictures, :path => "gallery", shallow: true do
    resources :pictures
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true    

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact form from GlamourHit",
      :to => ENV["EMAIL_MAILER"], #to be added
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :preview_picture
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/preview_picture.rb
class PreviewPicture < ActiveRecord::Base
  has_one :picture, dependent: :destroy
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.by_date
    order(created_at: :desc) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)
    @contact.request = request
    if @contact.deliver
      redirect_to '/'
    else
      render :new
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/packages_and_prices_controller.rb
class PackagesAndPricesController < ApplicationController
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def new
    @preview_picture = PreviewPicture.find(params[:preview_picture_id])
    @picture = Picture.new
  end

  def create
    @preview_picture = PreviewPicture.find(params[:preview_picture_id])
    @picture = @preview_picture.create_picture(picture_params)
    if @picture.save
      redirect_to "/gallery"
    else
      raise 'try again'
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.update(picture_params)
    id = @picture.id
    # redirect_to "/pictures/#{id}/edit"
    redirect_to preview_pictures_path
  end

  def picture_params
    params.require(:picture).permit(:image)
  end

end

app/controllers/preview_pictures_controller.rb
class PreviewPicturesController < ApplicationController

  def new
    @preview_picture = PreviewPicture.new
  end

  def create
    @preview_picture = PreviewPicture.create(preview_picture_params)
    id = @preview_picture.id
    redirect_to "/gallery/#{id}/pictures/new"
  end

  def show
    @preview_picture = PreviewPicture.find(params[:id])
  end

  def destroy
    @preview_picture = PreviewPicture.find(params[:id])
    @preview_picture.destroy
    if @preview_picture.destroyed?
        redirect_to preview_pictures_path
    else
        raise "Something went wrong"
    end
  end

  def edit
    @preview_picture = PreviewPicture.find(params[:id])
  end

  def update
    @preview_picture = PreviewPicture.find(params[:id])
    @preview_picture.update(preview_picture_params)
    id = @preview_picture.id
    redirect_to "/pictures/#{id}/edit"
    # redirect_to preview_pictures_path
  end

  def preview_picture_params
    params.require(:preview_picture).permit(:image)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/packages_and_prices_helper.rb
module PackagesAndPricesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/preview_pictures_helper.rb
module PreviewPicturesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/contacts/create.html.erb
<h3>Thank you for your message.</h3>
<p>I'll get back to you as soon as possible.</p>

app/views/contacts/new.html.erb
<section class='container'>
  <section id='contact'>
    <h3>Contact</h3>
    <p>Tel.: 07725911807<p>
    <a href='https://www.facebook.com/Glamourhit'><img src='<%= asset_path('facebook-icon.png') %>'></a>

   <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class="form-actions">
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
    <% end %>
  </section>
</section>

app/views/homepage/index.html.erb
<!-- Full Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>

  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" id='image1'></div>
    </div>
    <div class="item">
      <div class="fill" id='image2'></div>
    </div>
    <div class="item">
      <div class="fill" id='image3'></div>
    </div>
    <div class="item">
      <div class="fill" id='image4'></div>
    </div>
    <div class="item">
      <div class="fill" id='image5'></div>
    </div>
    <div class="item">
      <div class="fill" id='image6'></div>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse <% if current_page?(homepage_index_path) || current_page?(root_path) %>navbar-fixed-top <% else %>navbar-fixed-top unfixed-top<% end %>" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href='/' class='navbar-brand'><img src="<%= asset_path('Glamour Hit Logo OL.png') %>" /></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Service", services_path %>
        </li>
        <li>
          <%= link_to "Packages & Prices", packages_and_prices_path %>
        </li>
        <li>
          <%= link_to "Gallery", preview_pictures_path, :class => "gallery_js" %>
        </li>
        <li>
          <%= link_to "Contact", new_contact_path %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlamourHit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="London professional photographer captures beautiful pictures of models in boudoir and glamour style">
    <meta name="keywords" content="sexy, sensual, portraits, photographer, escorts, models, professional, London, GlamourHit, Photography">
    <%= favicon_link_tag 'favicon.ico' %>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render :partial => 'layouts/navbar' %>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/packages_and_prices/index.html.erb
<section id='packages_and_prices'>
  <img id='p_p_img' src="https://s3-eu-west-1.amazonaws.com/glamourhit/images/_MG_0665-Copy.jpg" />
  <article class='text_p_p'>
    <article>
      <h3>Deluxe</h3>
      <ul>
        <li>Free consultation:  discussing your needs, your style</li>
        <li>What to wear:  clothes, shoes, lingerie, accessories</li>
        <li>2 hours of intimate, relaxed and professional Photography in a private studio</li>
        <li>3 outfits</li> 
        <li>15 digital high resolution, air-brushed and edited images</li>
        <h5>£ 325</h5>
      </ul>
    </article>

    <article>
      <h3>Deluxe Pro</h3>
      <ul>
        <li>Professional makeup artist creates your perfect look (hair and make-up)</li>
        <li>Free consultation:  discussing your needs, your style</li> 
        <li>What to wear:  clothes, shoes, lingerie, accessories, including hints, tips and things to do the day before the photo shoot - ideal for professional models and escorts</li>
        <li>3 hours of intimate, relaxed and professional Photography in a private studio</li>
        <li>4 outfits</li>
        <li>25 digital high resolution air-brushed and edited images</li>
        <h5>£ 495</h5>
      </ul>
    </article>

    <article>
      <h3>Deluxe Ultimate</h3>
      <ul>
        <li>Professional makeup artist creates your perfect look (hair and make-up) for each set</li>
        <li>Free consultation:  discussing your needs, your style and your dream look</li> 
        <li>What to wear:  clothes, shoes, lingerie, accessories, including hints, tips and things to do the day before the photo shoot - ideal for professional models and escorts</li>
        <li>A half day of intimate, relaxed and professional Photography in a private studio</li>
        <li>5 outfits</li>
        <li>Glass of Champagne and buffet lunch during/after the shoot</li>
        <li>Luxurious matted print box with 10 x mounted 10” x 8” prints of your choice</li>
        <li>30 digital high resolution air-brushed and edited images on a personal USB stick</li>
        <h5>£ 895</h5>
      </ul>
    </article>

    <article>
      <h4>Special Offer</h4>
      <ul>
        <li>Bring a friend along on the same day for any additional Deluxe package and get 10% discount from the price of both packages</li>
        <li>Printed products, photo books, portfolio books also available on request</li>
      </ul>
    </article>

    <article id='p_p_requirements'>
      <ul>
        <li>All packages are for one person only.</li>
        <li>£100 deposit in advance required.</li>
        <li>Additional retouched photo @ £35 each.</li>
      </ul>
    </article>
  </article>

</section>

app/views/pictures/edit.html.erb
<% if user_signed_in? %>
  <h1>Edit a picture</h1>

  <%= form_for @picture do |f| %>
    <%= f.file_field :image %>
    <%= f.submit %>
  <% end %>
<% else %>
  <h1 id='must_signin'>You need to sign in</h1>
<% end %>

app/views/pictures/index.html.erb
<section class='container'>
    <% PreviewPicture.all.each do |preview_picture| %>

        <a class="fancybox" rel="group" href="#" ><%= image_tag preview_picture.image.url(:original), :class => 'grayscale' %></a>

    <% end %>
</section>

<% if user_signed_in? %>
<% end %>
  <%= link_to "Add Picture", new_preview_picture_path, :class => "add_preview_picture" %>

app/views/pictures/new.html.erb
<% if user_signed_in? %>
  <section class='main'>
    <h1>Add a picture (horizontal: 1620px x ~1080px - vertical: 720px x ~1080px)</h1>

    <%= form_for [@preview_picture, @picture], :html => { :multipart => true }, url: preview_picture_pictures_path do |f| %>
      <%= f.file_field :image %>
      <%= f.submit %>
    <% end %>
  </section>
<% else %>
  <h1 id='must_signin'>You need to sign in</h1>
<% end %>

app/views/preview_pictures/edit.html.erb
<% if user_signed_in? %>
  <section class='main'>
    <article id='form_preview'>
      <h3>Edit the picture's preview (250px x 250px)</h3>

      <%= form_for @preview_picture, html: {multipart: true} do |f| %>
        <%= f.file_field :image %>
        <%= f.submit %>
      <% end %>

    </article>
  </section>
<% else %>
  <h1 id='must_signin'>You need to sign in</h1>
<% end %>

app/views/preview_pictures/index.html.erb
<section class='container'>
  <article id='gallery'>
    <h1>Gallery</h1>
    <% PreviewPicture.all.by_date.each do |preview_picture| %>
      <a class="fancybox" rel="group" href="<%= preview_picture.picture.image.url(:original)%>" ><%= image_tag preview_picture.image.url(:original), :class => 'grayscale' %></a>
        <% if user_signed_in? %>
          <%= link_to "Delete #{preview_picture.id}", preview_picture_path(:id => preview_picture.id), method: :delete %>
        <% end %>
    <% end %>
  </article>
</section>

<% if user_signed_in? %>
  <%= link_to "Add Picture", new_preview_picture_path, :class => "add_preview_picture" %>
<% end %>

app/views/preview_pictures/new.html.erb
<% if user_signed_in? %>
  <section class='main'>
    <article id='form_preview'>
      <h3>Add the picture's preview (250px x 250px)</h3>

      <%= form_for @preview_picture, html: {multipart: true} do |f| %>
        <%= f.file_field :image %>
        <%= f.submit %>
      <% end %>

    </article>
  </section>
<% else %>
  <h1 id='must_signin'>You need to sign in</h1>
<% end %>

app/views/preview_pictures/show.html.erb
<section class='container'>
<% if user_signed_in? %>
  <a href="/gallery">Back to gallery</a>
<% end %>
</section>

app/views/services/index.html.erb
<article id='services'>
  <h1>The Service</h1>
  <p id='p_services'>
  	A Photo shoot at GlamourHit is not just a photography session, it`s a unique experience, a special event that every women deserves to have. This is the time and the place where we celebrate beauty and our sensual side.<br>
    GlamourHit creates sexy, sensuous and daring portraits, sometimes with a touch of the naughty, all of course with personal care and attention to detail and taste.<br>
    I’m Kristina, your professional photographer and I will guide you through each pose, I will know exactly which angles to cover when capturing your best and will tailor the shoot for your body type and your personality.<br>
    This is about you feeling comfortable and fabulous, so we work together and get to know each other to make sure that happens! This is also a great opportunity to pamper yourself, relax and express your feelings, your personality and your glamorous side.<br>
    It`s wonderful! ...When shall we start?<br>
    If you feel this truly uplifting experience is for you, then have a browse through the 3 Deluxe packages provided and simply choose the one which suits you, get in touch and we’ll do the rest.<br>
    Looking forward to seeing you... looking absolutely gorgeous.<br>
    <span class="signature">Kris xx</span>
  </p>
  <img src="https://s3-eu-west-1.amazonaws.com/glamourhit/images/_MG_0414.jpg" />
</article>